### ISSUE TITLE
Missing checks for song length from Kugou

### ISSUE THREAD

**Issue by hexchain** [ITJesse/UnblockNeteaseMusic#1]
For example, results for "Love wing bell" are all TV-sized from Kugou.

EDIT: sorry typo

**Comment by ITJesse** [comment]
Maybe you said "kugou".
But I can't find a comfortable way to increase the matching accuracy.

**Comment by hexchain** [comment]
Is it better to use album + songname as keyword for Kugou?

**Comment by ITJesse** [comment]
Could you please provide the exact song id?
I will do some research about matching rules before...

http://music.163.com/#/m/song?id=29722263

The "29722263" is song id.

**Comment by hexchain** [comment]
Song ID: 28638779, 32235958

I'm currently doing some experiments at my forked tree. Thank you!

**Comment by ITJesse** [comment]
Maybe netease buy the copyright : - )
