### ISSUE TITLE
New URL is null

### ISSUE THREAD

**Issue by steven7851** [ITJesse/UnblockNeteaseMusic#11]
有些歌曲直接连网易云可以正常播放，但是用代理就不能播
是不是伺服器在海外的关系？可是该代理不是能解决网易云的海外限制么

![](http://i.imgur.com/Zf3TdoY.png)

**Comment by ITJesse** [comment]
解决海外限制的原理是使用大陆服务器代理海外用户的流量。

关于 `New URL is null` 的问题，请提供重现步骤及以下信息：
1. 服务器区域
2. 歌曲 id
3. 客户端版本

**Comment by steven7851** [comment]
服务器区域在日本，那应该是这个问题了
能不譨让服务器使用代理连接 music.163.com 呢？

**Comment by steven7851** [comment]
我發現海外也能正常訪問API
API返回的地址如http://m2.music.126.net/IRNfMPZpAd_EL_oXIvtKnA==/1375489062254623.mp3

**Comment by ITJesse** [comment]
由你现在提供的情报判断，这个问题是因为你的服务器在海外。
跟网易云没有关系，请理解海外解锁的原理。
Unblock Youku 和本项目的设计初衷不同，请了解项目用途及自身需求后使用。
