### ISSUE TITLE
最新版无法安装

### ISSUE THREAD

**Issue by steven7851** [ITJesse/UnblockNeteaseMusic#12]
Google到解法了，安装时加上 --unsafe-perm 参数就解决了，不好意思还开个 issue 打扰 -_-

--------------
安装最新版 3.0.5 时，会进入这个无限 loop
![untitled](https://user-images.githubusercontent.com/6252238/30602411-10c2cf9e-9d97-11e7-9c1d-ca4cf439efdc.jpg)

**Comment by ITJesse** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by AndyChen2005121** [comment]
???
