### ISSUE TITLE
Windows 如何安装？

### ISSUE THREAD

**Issue by leewp14** [ITJesse/UnblockNeteaseMusic#13]
看起来在linux安装应该没问题 不过Windows那个安装nginx那一部分好像不怎么ok 有详细教程吗？
我使用的nginx是http://nginx-win.ecsds.eu 的
得到error：` [emerg] "proxy_cache" zone "STATIC" is unknown`

**Comment by leewp14** [comment]
成功解决了 可以运行但无法操作 有办法看log吗？

**Comment by ITJesse** [comment]
I am not sure if these code will run on the Windows correctly.
Maybe you can find the solution in some nginx documents.

**Comment by leewp14** [comment]
I think this stuff rather is hard to get it run on windows. 
the subs-filter module is not included and only can be included by self compile nginx, which is not possible (or rather not easy) on Windows client. 
It is included in this unofficial version of windows nginx http://nginx-win.ecsds.eu/ but things seems to get messed. 
Perhaps the only way to get it work on windows is make a .so nginx dynamic subs-filter module using a linux machine. https://www.nginx.com/blog/nginx-dynamic-modules-how-they-work/
I think I will try to do this on Linux first. Will close this issue. Thanks :smiley:
