### ISSUE TITLE
这个东东怎么用？

### ISSUE THREAD

**Issue by AndyChen2005121** [ITJesse/UnblockNeteaseMusic#16]
> 执行`unblockneteasemusic`的时候。。。
>
> unblockneteasemusic --username AndyChen2005121 --password ******
> Web API enabled.
> /usr/local/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31
>         throw new Error('Please install sqlite3 package manually');
>         ^
> 
> **Error: Please install sqlite3 package manually**
>     at new ConnectionManager (/usr/local/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:31:15)
>     at new SqliteDialect (/usr/local/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
>     at new Sequelize (/usr/local/lib/node_modules/unblock-netease-music/node_modules/sequelize/lib/sequelize.js:233:20)
>     at Object.<anonymous> (/usr/local/lib/node_modules/unblock-netease-music/dist/models/index.js:30:19)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/unblock-netease-music/dist/controllers/modify/dead.js:8:15)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/unblock-netease-music/dist/controllers/modify/player.js:12:13)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/unblock-netease-music/dist/controllers/modify/index.js:7:15)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/unblock-netease-music/dist/controllers/index.js:8:15)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)
>     at Module.load (module.js:554:32)
>     at tryModuleLoad (module.js:497:12)
>     at Function.Module._load (module.js:489:3)
>     at Module.require (module.js:579:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/usr/local/lib/node_modules/unblock-netease-music/dist/app.js:39:20)
>     at Module._compile (module.js:635:30)
>     at Object.Module._extensions..js (module.js:646:10)

这是怎么回事？我按照 #15 中你说明的方法弄了弄，装了sqlite3， 用npm重装了这个项目，还是卡在这个问题。
求教！！！

**Comment by ITJesse** [comment]
https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by AndyChen2005121** [comment]
hey，我说了，**你这个文档的方法行不通！！！**
至少告诉我该怎么弄>_<
