### ISSUE TITLE
Song From Kugou is not the right song

### ISSUE THREAD

**Issue by jeffssss** [ITJesse/UnblockNeteaseMusic#2]
http://music.163.com/#/m/song?id=401712013

work - rihanna,Drake
in console:
```
Song name: Work
Artist: Rihanna
Player API Injected
New URL is http://fs.web.kugou.com/0c7b90f56967fe37e5a410e6693010fa/570f9bbc/G055/M09/04/19/dw0DAFb4nE2AfxqzADW2VUmPWlI124.mp3
```

song from kugou is live version.

**Comment by ITJesse** [comment]
get√

**Comment by evindu** [comment]
@ITJesse  是不是kugou的歌 不能播放，我有些歌无法播放

**Comment by ITJesse** [comment]
请提供下不能播放的歌曲的具体信息，以及 songId。 @evindu

**Comment by evindu** [comment]
@ITJesse http://music.163.com/#/album?id=2771296

**Comment by ITJesse** [comment]
@evindu 

```
Song name: 作曲家
Artist: 李荣浩
  --> POST /eapi/song/lyric 200 92ms 1.45kb
No resource found on kugou.
No resource found on netease.
No resource.
  --> POST /eapi/song/enhance/player/url 200 276ms 165b
  <-- POST /eapi/song/enhance/player/url
  <-- POST /eapi/song/lyric
  --> POST /eapi/song/lyric 200 88ms 1.4kb
  <-- POST /eapi/song/lyric
  --> POST /eapi/song/lyric 200 109ms 1.4kb
Song name: 哎呀
Artist: 李荣浩
No resource found on kugou.
No resource found on netease.
No resource.
```

**Comment by evindu** [comment]
@ITJesse  好吧 但是不知道为什么 他的 https://github.com/Chion82/163-music-unlock可以，但是他github上公开的脚本已经无法获取到歌曲文件的播放地址。他公共服务器上使用了其他方法。

**Comment by ITJesse** [comment]
@evindu 
> 108.61.201.11 Vultr Tokyo
> 103.27.77.201 香港SLHK

不知道你用的是哪一个 IP，刚刚尝试了下发现并不能播放。

**Comment by evindu** [comment]
@ITJesse  http://music.163.com/#/song?id=29572501 这首 就可以播放但是你的脚本好像不行（我用的108.61.201.11 Vultr Tokyo）  还有李荣浩作曲家 那首歌可以播放 但是你的脚本好像不行

**Comment by ITJesse** [comment]
@evindu 谢谢你的反馈，我会抽时间测试。

**Comment by evindu** [comment]
@ITJesse 应该不是你脚本的问题  因为我用 yanunon 的api 下载这首
http://music.163.com/#/song?id=29572501 歌获得的链接也是下载不了的。。。

**Comment by GeamC** [comment]
用这边的https://github.com/YiuChoi/Unlock163Music 可以下载上面的歌，而且好像用的不是kugou的源。

**Comment by ITJesse** [comment]
@GeamC 这是用 Xposed 框架调用的 APP 内置方法实现的。纯黑盒调用。

**Comment by ITJesse** [comment]
@jeffssss 
Add some other mirror site...

**Comment by evindu** [comment]
@ITJesse  unblock-netease-music 更新了？

**Comment by ITJesse** [comment]
Fixed!
