### ISSUE TITLE
配置上的一些问题

### ISSUE THREAD

**Issue by 1kevin335200** [ITJesse/UnblockNeteaseMusic#21]
自己能力不足，配了半天还是没有成功（nginx不熟悉），希望能咨询一下，不胜感激
1.nginx配置位置：一开始提示subs_filter之类参数不认，Google后知道需要添加Substitutions插件手动编译nginx，现在已经解决了。但是不知道放在哪里，直接内容替换/etc/nginx.conf肯定不行，将server部分插入/etc/nginx.conf似乎也不行，内容替换/etc/nginx/site-enabled/default也不对orz
2.本机调试，所以hosts写了127.0.0.1 music.163.com，但也许因为第一条原因没成功，现在访问music.163.com只有nginx欢迎页面。自然nginx并没有调用8123端口和插件一起工作。

题外话：最终是想在路由器上配好，让所有设备解除海外限制即可，请问可行性如何？比如安卓端

**Comment by ITJesse** [comment]
1. Debian 系直接安装 nginx-extras 即可，其他系统请从源码编译。
2. 目前 hosts 的方式已经失效，请参考 Readme 中的教程注入插件
3. 因为手头没有安卓设备，所以暂时没有支持计划。
4. 路由器配置的话，OpenWRT 系列应该很难实现，x86 软路由则没有问题。
